# Generated by Django 2.2.12 on 2021-04-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusterNum',
            fields=[
                ('username', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Personality.registration_details', unique=True)),
                ('clusNo', models.IntegerField(null=True, verbose_name='clusNo')),
            ],
        ),
    ]
