# Generated by Django 2.2.12 on 2021-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personality', '0002_clusternum'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusternum',
            name='agreeable',
            field=models.FloatField(null=True, verbose_name='agreeable'),
        ),
        migrations.AddField(
            model_name='clusternum',
            name='conscientious',
            field=models.FloatField(null=True, verbose_name='conscientious'),
        ),
        migrations.AddField(
            model_name='clusternum',
            name='extroversion',
            field=models.FloatField(null=True, verbose_name='extroversion'),
        ),
        migrations.AddField(
            model_name='clusternum',
            name='neurotic',
            field=models.FloatField(null=True, verbose_name='neurotic'),
        ),
        migrations.AddField(
            model_name='clusternum',
            name='openness',
            field=models.FloatField(null=True, verbose_name='openness'),
        ),
    ]
